import Header from "@/components/header";
import Footer from "@/components/footer";
import { Button } from "@/components/ui/button";
import { Eye, Dumbbell, BarChart3, ArrowRight } from "lucide-react";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Header />

      <main>
        {/* Hero Section */}
        <section className="relative flex min-h-[85vh] items-center justify-center overflow-hidden px-5 pt-10 sm:px-8">
          <div className="mx-auto max-w-[1200px] text-center">
            <div className="fade-in">
              <div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full bg-white px-4 py-1.5 text-sm text-[rgba(32,32,32,0.75)] shadow-[0px_2px_4px_-1px_rgba(1,65,99,0.08)] border border-[rgba(32,32,32,0.08)]">
                <span className="inline-block h-2 w-2 rounded-full bg-gradient-to-r from-[#1DA1F2] to-[#0d6efd]" />
                Gait Analysis Platform
              </div>
            </div>

            <h1
              className="fade-in mx-auto max-w-3xl text-[32px] leading-[96%] font-bold tracking-[-0.05em] sm:text-[48px] md:text-[64px]"
              style={{ animationDelay: "0.1s" }}
            >
              Understand movement.{" "}
              <span className="text-gradient">Protect health.</span>
            </h1>

            <p
              className="fade-in mx-auto mt-6 max-w-xl text-base leading-[140%] text-[rgba(32,32,32,0.75)] sm:text-lg"
              style={{ animationDelay: "0.2s" }}
            >
              Upload a walking video and get AI-powered gait analysis with
              personalized exercise recommendations in seconds.
            </p>

            <div
              className="fade-in mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"
              style={{ animationDelay: "0.3s" }}
            >
              <Link href="/analyze">
                <Button variant="modern-primary" size="modern-xl" className="gap-2 px-6">
                  Analyze Your Gait
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
              <Link href="#how-it-works">
                <Button variant="modern-outline" size="modern-xl" className="px-6">
                  Learn More
                </Button>
              </Link>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="px-5 py-20 sm:px-8">
          <div className="mx-auto max-w-[1200px]">
            <div className="mb-14 text-center">
              <h2 className="h2-style text-[#202020]">
                Built for <span className="text-gradient">precision</span>
              </h2>
              <p className="mx-auto mt-4 max-w-lg text-base leading-[140%] text-[rgba(32,32,32,0.75)]">
                Everything you need to analyze, monitor, and improve gait
                patterns.
              </p>
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <div className="platform-feature-card rounded-[10px] border border-[rgba(32,32,32,0.06)] p-6">
                <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-full bg-gradient-to-b from-[#E0F5FF] to-white">
                  <Eye className="h-5 w-5 text-[#1DA1F2]" />
                </div>
                <h3 className="mb-2 text-xl leading-[1.15] font-bold tracking-[-0.01rem] text-[#202020]">
                  AI-Powered Vision
                </h3>
                <p className="text-base leading-[140%] text-[rgba(32,32,32,0.75)]">
                  NVIDIA VLM analyzes your walking video frame by frame to identify gait patterns and abnormalities.
                </p>
              </div>

              <div className="platform-feature-card rounded-[10px] border border-[rgba(32,32,32,0.06)] p-6">
                <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-full bg-gradient-to-b from-[#E0F5FF] to-white">
                  <Dumbbell className="h-5 w-5 text-[#1DA1F2]" />
                </div>
                <h3 className="mb-2 text-xl leading-[1.15] font-bold tracking-[-0.01rem] text-[#202020]">
                  Personalized Coaching
                </h3>
                <p className="text-base leading-[140%] text-[rgba(32,32,32,0.75)]">
                  Get a custom exercise plan generated by AI, targeting your specific movement issues.
                </p>
              </div>

              <div className="platform-feature-card rounded-[10px] border border-[rgba(32,32,32,0.06)] p-6">
                <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-full bg-gradient-to-b from-[#E0F5FF] to-white">
                  <BarChart3 className="h-5 w-5 text-[#1DA1F2]" />
                </div>
                <h3 className="mb-2 text-xl leading-[1.15] font-bold tracking-[-0.01rem] text-[#202020]">
                  Detailed Breakdown
                </h3>
                <p className="text-base leading-[140%] text-[rgba(32,32,32,0.75)]">
                  See left vs right side comparisons, asymmetry detection, and severity scoring.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section id="how-it-works" className="px-5 py-20 sm:px-8">
          <div className="mx-auto max-w-[1200px]">
            <div className="mb-14 text-center">
              <h2 className="h2-style text-[#202020]">
                How it <span className="text-gradient">works</span>
              </h2>
              <p className="mx-auto mt-4 max-w-lg text-base leading-[140%] text-[rgba(32,32,32,0.75)]">
                Three simple steps to get started with GaitGuard.
              </p>
            </div>

            <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
              {[
                {
                  step: "01",
                  title: "Upload",
                  description: "Record or upload a video of yourself walking. Our system accepts webcam recordings or file uploads.",
                },
                {
                  step: "02",
                  title: "AI Analysis",
                  description: "NVIDIA's vision AI analyzes your gait patterns, detecting asymmetries, postural issues, and movement abnormalities.",
                },
                {
                  step: "03",
                  title: "Get Your Plan",
                  description: "Receive a personalized exercise program with step-by-step instructions tailored to your specific gait patterns.",
                },
              ].map((item) => (
                <div key={item.step} className="platform-feature-card rounded-[10px] border border-[rgba(32,32,32,0.06)] p-6 text-center">
                  <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full border-[1.054px] border-[#202020] bg-gradient-to-b from-[#515151] to-[#202020] shadow-[0_0_1.054px_3.163px_#494949_inset,0_6.325px_5.271px_0_rgba(0,0,0,0.55)_inset]">
                    <span className="text-sm font-bold text-white">{item.step}</span>
                  </div>
                  <h3 className="mb-2 text-xl leading-[1.15] font-bold tracking-[-0.01rem] text-[#202020]">
                    {item.title}
                  </h3>
                  <p className="text-base leading-[140%] text-[rgba(32,32,32,0.75)]">
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="px-5 py-20 sm:px-8">
          <div className="mx-auto max-w-[800px]">
            <div className="rounded-[16px] bg-[linear-gradient(180deg,#E0F5FF_0%,#F0FAFF_44.95%,#FFFFFF_100%)] border border-[rgba(32,32,32,0.06)] p-10 text-center sm:p-16">
              <h2 className="h2-style text-[#202020]">
                Ready to improve your <span className="text-gradient">movement</span>?
              </h2>
              <p className="mx-auto mt-4 max-w-md text-base leading-[140%] text-[rgba(32,32,32,0.75)]">
                Join GaitGuard today and take the first step towards better gait
                health.
              </p>
              <div className="mt-8">
                <Link href="/analyze">
                  <Button variant="modern-primary" size="modern-xl" className="gap-2 px-6">
                    Start Free Analysis
                    <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
